#!/bin/sh

set -e

case "$1" in
    install)
        dpkg-divert --rename --package gnome-theme-reddragon \
                    --divert /usr/share/gnome-shell/theme/gnome-shell.css.original \
                    --add /usr/share/gnome-shell/theme/gnome-shell.css
    ;;
    
    upgrade|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

# Automatically added by dh_installdeb/10.7.2ubuntu2~ubuntu16.04.1~c42.ppa1
dpkg-maintscript-helper dir_to_symlink /usr/share/themes/Kali-X/gtk-3.0 gtk-3.20 2016.1.0 -- "$@"
# End automatically added section

